permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: pygments
encoding: utf-8

kramdown:
  input: GFM

# 作者信息
author:
  name: zhisong
  email: 1060201919@qq.com
  link: https://changzhisong.github.io/
  weibo: https://weibo.com/5017438529
  github: https://github.com/changzhisong

# 站点信息
title: zhisong
description: 个人博客(Jekyll);整理、记载关于工具/资源/生活/技术/读书/影音等经验和思考;
url: https://changzhisong.github.io/
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: https://raw.githubusercontent.com/Changzhisong/Changzhisong.github.io/master/assets/images/czs-icon.jpg
# favicon: https://raw.githubusercontent.com/Changzhisong/Changzhisong.github.io/master/assets/images/czs-icon.jpg

# google analytics 设置
ga:
  id: UA-86109050-1
  url: changzhisong.github.io

# disqus 设置
#disqus:
  #shortname: zhisongblog

#rake configuration on 2017-12-16
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: atom
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/changzhisong.github.com/
