permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 晚晴幽草
  email: jeffjade@163.com
  link: http://www.jeffjade.com
  weibo: http://weibo.com/3235949794
  github: http://github.com/nicejade

# 站点信息
title: 锦瑟华年博客
description: 锦瑟华年博客
url: http://nicejade.github.io
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: https://ssl.moefq.com/images/2015/11/11/a26afec168d67edeeff1fe1526fb22a0.jpg
favicon: http://www.jeffjade.com/img/xuan.ico

# google analytics 设置
ga:
  id: UA-54767140-1
  url: yansu.org

# disqus 设置
disqus:
  shortname: suyan-zh
